allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  es5-ext: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - es5-ext
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd
